# Generated by Django 3.1.2 on 2020-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('seq',)},
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='question1_choice_id',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='question2_choice_id',
            new_name='question10',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='question3_choice_id',
            new_name='question2',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='city',
            field=models.CharField(default='Enter City', max_length=100),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question11',
            field=models.CharField(default='Health monitoring', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question12',
            field=models.CharField(default='Rs. 7000 to Rs. 10000', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question3',
            field=models.CharField(default='Please enter', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question4',
            field=models.CharField(default='Self', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question5',
            field=models.CharField(default='Medicine Procurement', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question7',
            field=models.CharField(default='Weekly', max_length=250),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='question9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='comments',
            field=models.CharField(default='Enter Comment', max_length=250),
        ),
    ]
