# Generated by Django 3.1.2 on 2020-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201027_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question1',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question10',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question2',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question6',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question8',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question9',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='res_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
