# Generated by Django 3.1.2 on 2020-10-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20201027_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question1',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question10',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question2',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question6',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question8',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question9',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
