# Generated by Django 3.1.2 on 2020-10-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20201027_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=100)),
                ('comments', models.CharField(default='Enter Comment', max_length=250)),
                ('res_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
